### PR TITLE
Initial reproducible research template

### PR DESCRIPTION
**Pull request by bobturneruk**
I've done a quick job on this following the ML meeting (2021/03/29). Feedback appreciated - this will need to evolve after being merged to handle a broader range of use cases, but I hope it will support the hackathon outputs.

### CODE REVIEW

**Review by Priscilla-AL — APPROVED** [review]
Looks good to me

**Comment by bobturneruk** [comment]
Thanks @Priscilla-AL !

**Comment by bobturneruk** [comment]
I'll merge with 3 approvals.

**Review by sserurich — APPROVED** [review]
This looks fine. However seems I didn't see the directories that were mentioned in the presentation i.e notebooks, data (raw/clean) and figures in the repo which might have been intentional since I saw instructions in the readme file

**Review by lilly-muyama — COMMENTED** [review]
@bobturneruk I thought the files/folders would be reflecting the structure as stated in the readme file. For instance, I don't see the data folder. Also, would it be okay if we had two separate folders for the notebooks and the python files e.g. notebooks and src. A folder where we save and load models from would also be nice. What do you think?

**Comment by bobturneruk** [comment]
Sorry about the lack of `data/` folder - my mistake - should now be fixed. I've also seperates `notebooks/` and `scripts/`.

**Comment by bobturneruk** [comment]
Really good idea on the `models/` folder @lilly-muyama - interested in your thoughts on the guidance added.

**Review by lilly-muyama — APPROVED** [review]
LGTM

**Pull request merged**
