### PR TITLE
Calibration rf

### PR DESCRIPTION
**Pull request by lilly-muyama**
WHAT DOES THIS PR DO?
This PR refactors some of the hackathon code to reflect the new agreed-upon structure

WHAT JIRA STORY/TASK IS RELATED TO THIS PR?
N/A

WHAT IS THE LINK TO THE PR BRANCH

HOW DO I TEST OUT THIS PR?
To run this code, you need to have Python>=3.7 installed on your system.
- Git clone this repo and run these commands
- `cd calibration_rf_l`
- `python -m venv env` for Windows OR `python3 -m venv env` for linux/macOS
- `env\scripts\activate` for Windows OR `source env/bin/activate` for linux/macOS
- `pip install -r requirements.txt`
- `jupyter notebook`
- Open `random_forest.ipynb` and select `run all`

### CODE REVIEW

**Comment by bobturneruk** [comment]
Requires Python>=3.7.

**Comment by bobturneruk** [comment]
It would be good to include a readme in the `calibration_rf_l` folder as per the template. Most of the content is boilerplate + what's written under "how do I test this PR", above. Also please include a license.

**Comment by bobturneruk** [comment]
I get this error when trying to run `random_forest.ipynb`

```
FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/train_set.csv'
```

Does the data need to be included in the repository, or is it too big?

**Comment by lilly-muyama** [comment]
> 
> 
> I get this error when trying to run `random_forest.ipynb`
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/train_set.csv'
> ```
> 
> Does the data need to be included in the repository, or is it too big?

@bobturneruk I've now added the data

**Comment by lilly-muyama** [comment]
> 
> 
> It would be good to include a readme in the `calibration_rf_l` folder as per the template. Most of the content is boilerplate + what's written under "how do I test this PR", above. Also please include a license.

Done @bobturneruk

**Comment by lilly-muyama** [comment]
> 
> 
> Requires Python>=3.7.

I have added this to the PR description and the readme file

**Review by bobturneruk — APPROVED** [review]
I think this is really good and should be merged. It runs on my laptop when I follow the instructions. 

It has prompted me to think of some things to add to the template in a future PR, which I'll note here and act on later:

- Some method of confirming that the expected results are produced e.g. a "frozen" version of the output to compare with, or a regression test.
- Instructions for myBinder.
- More information on how to store models with `joblib`. I may need some help with this!

**Comment by bobturneruk** [comment]
@lilly-muyama - I could ask someone unfamiliar with the project to give some feedback to see how easy it is to understand for them?

**Comment by lilly-muyama** [comment]
> 
> 
> @lilly-muyama - I could ask someone unfamiliar with the project to give some feedback to see how easy it is to understand for them?

@bobturneruk That's okay

**Comment by lilly-muyama** [comment]
> 
> 
> I think this is really good and should be merged. It runs on my laptop when I follow the instructions.
> 
> It has prompted me to think of some things to add to the template in a future PR, which I'll note here and act on later:
> 
>     * Some method of confirming that the expected results are produced e.g. a "frozen" version of the output to compare with, or a regression test.
> 
>     * Instructions for myBinder.
> 
>     * More information on how to store models with `joblib`. I may need some help with this!

Sounds good @bobturneruk

**Comment by bobturneruk** [comment]
Another thought - it would be good to have some way of capturing the "provenance" of the input data i.e. where it came from and when, how trustworthy is it? I'll have a think about how to put this in the template.

**Pull request merged**
